#define QUAD_DEFAULT_ADDRESS 0x6D

enum SF_AVAILABLE_QUAD_RELAYS {
  RELAY_ONE           = 0x01,
  RELAY_TWO,
  RELAY_THREE,
  RELAY_FOUR,

};

enum SF_QUAD_RELAY_COMMANDS {
  TOGGLE_RELAY_ONE    = 0x01,
  TOGGLE_RELAY_TWO,
  TOGGLE_RELAY_THREE,
  TOGGLE_RELAY_FOUR,
  RELAY_ONE_STATUS,
  RELAY_TWO_STATUS,
  RELAY_THREE_STATUS,
  RELAY_FOUR_STATUS,
  TURN_ALL_OFF        = 0xA,
  TURN_ALL_ON,       
  TOGGLE_ALL,
};

enum SF_QUAD_RELAY_STATUS {
  QUAD_RELAY_OFF      = 0,
  QUAD_RELAY_ON       = 15  
};
